tests: Avoid the InterpreterNotFound errors
Turns out we detect if we run on Fedora, and enable python3 related
checks only on Fedora. Use the existing mechanism to run the *-py36 tox
envs only when python 3 is available.

We should not see now these annoying errors:

    ERROR: InterpreterNotFound: python3.6

Change-Id: I7242739c05f2c896f9b148789ba803d2c91f8e71
Signed-off-by: Nir Soffer <nsoffer@redhat.com>