tests: Add concurrency test
Add a test simulating extreme concurrent usage of the managed volume db.
In the real application we will never have such concurrency since number
of api request threads is bounded, and attaching a volume takes several
seconds.

Tests on my idle laptop show that the default sqlite3 timeout works fine
for this extreme test:

Python 2.7:
Added 100 volumes with 10 concurrent threads in 1.624959 seconds (0.016250 seconds/op)

Python 3.6:
Added 100 volumes with 10 concurrent threads in 1.757661 seconds (0.017577 seconds/op)

Running on overloaded CI slaves we had one random failure in about 10
runs:

concurrent.py              202 ERROR    FINISH thread <Thread(Thread-14, started daemon 140186725906176)> failed
Traceback (most recent call last):
  File "/home/jenkins/workspace/vdsm_standard-check-patch/vdsm/lib/vdsm/common/concurrent.py", line 195, in run
    ret = func(*args, **kwargs)
  File "/home/jenkins/workspace/vdsm_standard-check-patch/vdsm/tests/storage/managedvolumedb_test.py", line 165, in run
    db.add_volume(vol_id, {"connection": vol_id})
  File "/home/jenkins/workspace/vdsm_standard-check-patch/vdsm/lib/vdsm/storage/managedvolumedb.py", line 180, in add_volume
    self._conn.execute(sql, (vol_id, conn_info_json))
OperationalError: database is locked

concurrent.py              202 ERROR    FINISH thread <Thread(Thread-11, started daemon 140186954176256)> failed
Traceback (most recent call last):
  File "/home/jenkins/workspace/vdsm_standard-check-patch/vdsm/lib/vdsm/common/concurrent.py", line 195, in run
    ret = func(*args, **kwargs)
  File "/home/jenkins/workspace/vdsm_standard-check-patch/vdsm/tests/storage/managedvolumedb_test.py", line 175, in run
    attachment={"attachment": vol_id})
  File "/home/jenkins/workspace/vdsm_standard-check-patch/vdsm/lib/vdsm/storage/managedvolumedb.py", line 207, in update_volume
    vol_id))
OperationalError: database is locked

Since the CI is not stable environment for such stress tests, and the
test may take 12 seconds on the CI, I marked it as slow test.

To run the tests locally use:

    tox -e storage-py27,storage-py36 -- -m slow

If we see these errors in real system we may need to increase sqlite3
connection timeout:
https://docs.python.org/2/library/sqlite3.html#sqlite3.connect

Change-Id: Ia33a379db75ba19ea39071f8af13f88b4f791414
Signed-off-by: Nir Soffer <nsoffer@redhat.com>