tests: Mark test_ip_info as broken_on_ci
This test fails randomly on ovirt CI for months. I'm tired of restarting
builds because of this failure.

The test fails with this error:

    AssertionError: Tuples differ: ('192.0.2.2', '255.255.255.0',... != ('192.0.2.2', '255.255.255.0',...

    First differing element 2:
    ['192.0.2.2/24', '198.51.100.11/32', '192.0.2.3/24']
    ['192.0.2.2/24', '198.51.100.9/24', '198.51.100.11/32', '192.0.2.3/24']

      ('192.0.2.2',
       '255.255.255.0',
    -  ['192.0.2.2/24', '198.51.100.11/32', '192.0.2.3/24'],
    +  ['192.0.2.2/24', '198.51.100.9/24', '198.51.100.11/32', '192.0.2.3/24'],
    ?                  +++++++++++++++++++

       ['2607:f0d0:1002:51::4/64'])

Change-Id: I7670d7ac866848fd895d7602b3884a52d0723338
Signed-off-by: Nir Soffer <nsoffer@redhat.com>