concurrent: Log threads life cycle
We have many threads without any logging, starting and finishing
silently, and adding logging to all code starting threads is too much
work and error prone.

This patch adds standard logs for thread life cycle. Now each thread
will have these debug logs:

    2017-01-08 15:14:15,880 DEBUG (Thread-520) [root] START thread
    <Thread(Thread-520, started daemon 140257637971712)>
    (func=<function run at 0x7f9047b0ade8>, args=(1, 2), kwargs={'a': 3, 'b': 4})
    (concurrent:183)

    2017-01-08 15:14:15,880 DEBUG (Thread-520) [root] FINISH thread
    <Thread(Thread-520, started daemon 140257637971712)> (concurrent:186)

If a thread function raises, we will have this traceback:

    2017-01-08 15:22:01,034 ERROR (Thread-7) [root] FINISH thread
    <Thread(Thread-7, started daemon 140366796183296)> failed (concurrent:189)
    Traceback (most recent call last):
      File "/home/nsoffer/src/vdsm/lib/vdsm/concurrent.py", line 185, in run
	ret = func(*args, **kwargs)
      File "/home/nsoffer/src/vdsm/tests/concurrentTests.py", line 264, in run
	raise RuntimeError("Threads are evil")
    RuntimeError: Threads are evil

We are not using utils.traceback now, so the noisy test showing a
traceback on stderr was fixed, and we are also testing logging during
successful run.

Change-Id: Ic99b70f1759ea014505e13948fa93b0c8b7ed82d
Signed-off-by: Nir Soffer <nsoffer@redhat.com>