network: nmstate: Package vdsm/network/nmstate
Since nmstate was moved to new package in:

commit 15f0bd04c3ef8daf32fb75bdf51839aef241b185
Author: Ales Musil <amusil@redhat.com>
Date:   Thu Jun 25 11:59:30 2020 +0200

    net, nmstate: Move nmstate to its own module

supervdsm fail to start with this error:

    ImportError: cannot import name 'nmstate'

Fix by adding the necessary automake and autoconf magic so the new code
is packaged and installed on the host.

Change-Id: Ie6c28f28a4a776c3325117bcf71c261a58d07ce8
Signed-off-by: Nir Soffer <nsoffer@redhat.com>